### ISSUE TITLE
GDG Sacramento DevFest

### ISSUE THREAD

**Issue by kahluagenie** [gdgsacramento/raffleapp-angular#1]
We will keep track of important items in this issue.

**Comment by alcfeoh** [comment]
Steps:

Install NODE JS from nodejs.org
Run npm install -g @angular/cli
Use git to checkout our project from: https://github.com/gdgsacramento/raffleapp-angular
Open a terminal in your folder project and run: npm install
Run ng serve
Go to localhost:4200 in your browser and see your app up and running

**Comment by alcfeoh** [comment]
Slides with all explanations can found here: https://docs.google.com/presentation/d/1qMRzcWT4FL8do_Btz5QQXMp81v5Pz6AJNqsGgJ3N7-8/edit?usp=sharing
